// Pure JS seed data. Icons are stored as lucide-react component name strings.
export const seedData = {
  services: [
    {
      icon: "Users",
      number: "01",
      title: "INFLUENCER\nMARKETING",
      tagline: "End to end creator campaigns that convert",
      color: "#ffffff",
      tag: "Most Popular",
      items: [
        "End to end creator management",
        "Data driven shortlisting",
        "Strategic content planning",
        "Performance tracking & reporting",
      ],
      detail: {
        what: "Our influencer marketing service is a fully managed solution — we handle everything so your team doesn't have to. From identifying creators who genuinely resonate with your audience to scripting briefs, coordinating shoots, reviewing content, and reporting results.",
        who: "Gaming brands, tech launches, app installs, e-commerce, and any product category targeting Gen Z & millennials.",
        how: [
          "Deep audience analysis & creator shortlisting",
          "Brief creation, scripting & creative direction",
          "Contract negotiation & licensing",
          "Content review cycles & live tracking dashboard",
          "Post-campaign analytics with CPV, reach & engagement breakdown",
        ],
        perfectFor: [
          "Performance ads",
          "Product launches",
          "App installs",
          "Brand awareness at scale",
        ],
      },
    },
    {
      icon: "BarChart3",
      number: "02",
      title: "PERFORMANCE\nMARKETING",
      tagline: "High intent channels traditional agencies miss",
      color: "#a78bfa",
      tag: "High ROI",
      items: [
        "OEM Ads (device level placements)",
        "Preload Installs",
        "CTV Advertising",
      ],
      detail: {
        what: "We run paid performance campaigns across non-traditional but ultra high intent channels — OEM phone ads that appear the moment a user first boots their device, preload installs that ship your app with the phone itself, and CTV spots on smart TVs reaching households during prime time.",
        who: "App developers, gaming studios, fintech, and brands wanting guaranteed eyeballs with measurable ROI.",
        how: [
          "OEM partner network setup & campaign configuration",
          "Preload deal negotiation with device manufacturers",
          "CTV creative production & inventory buying",
          "Real time performance dashboard with ROAS tracking",
          "A/B testing creatives for cost-per-install optimization",
        ],
        perfectFor: [
          "App installs at scale",
          "New market entry",
          "Performance-first campaigns",
          "Guaranteed reach",
        ],
      },
    },
    {
      icon: "Star",
      number: "03",
      title: "TALENT\nMANAGEMENT",
      tagline: "We grow creators into brands",
      color: "#fbbf24",
      tag: "Full Service",
      items: [
        "Talent growth & development strategy",
        "Brand collaboration management",
        "Dedicated support & deal flow",
      ],
      detail: {
        what: "We represent gaming and lifestyle creators end to end. Our team handles inbound brand enquiries, negotiates deals, manages deliverables, and coaches creators on content strategy — so they can focus on making great content.",
        who: "Creators with 10K–10M+ followers looking to monetize, and brands looking for authentic long-term creator partnerships.",
        how: [
          "Creator audit & growth gap analysis",
          "Monetization roadmap & brand pitch deck",
          "Inbound deal filtering & negotiation",
          "Contract management & deliverable tracking",
          "Quarterly performance reviews & strategy recalibration",
        ],
        perfectFor: [
          "Long-term brand ambassadors",
          "Whitelisted creator content",
          "Affiliate campaigns",
          "Creator-led launches",
        ],
      },
    },
  ],

  caseStudies: [
    {
      num: "01",
      brand: "WEPLAY",
      category: "Gaming App · Influencer Marketing",
      color: "#6C3CE1",
      accentLight: "#a78bfa",
      objective: "Build a dedicated gaming audience through high engagement Shorts promotions.",
      strategy: "Activated top performing gaming channels with relatable short form content to spark curiosity and maximize reach.",
      execution: [
        "Multiple creator led short videos across YouTube Shorts and Instagram Reels",
        "Audience specific hooks focusing on immersive gameplay experience",
        "Momentum based posting schedule to maintain ongoing buzz",
      ],
      stats: [
        { value: "200K+", label: "Views", icon: "Eye" },
        { value: "₹0.15", label: "CPV", icon: "IndianRupee" },
        { value: "20K+", label: "Likes", icon: "ThumbsUp" },
        { value: "2K+", label: "Installs", icon: "Download" },
      ],
      fullDetail: {
        background: "WePlay was an emerging gaming platform looking to carve a niche in India's saturated mobile gaming market. The challenge: build brand awareness and drive app installs without a massive ad budget.",
        approach: "We identified mid-tier gaming creators (100K–500K subscribers) whose audiences had the highest overlap with WePlay's target demographic — competitive mobile gamers aged 16–28. Rather than one big creator push, we activated a cluster of 8 creators simultaneously to create a trending perception.",
        results: "The campaign delivered 200K+ views at an industry-beating ₹0.15 CPV, proving that smart creator selection outperforms raw spend. The 2K+ organic installs came entirely from creator CTAs — zero paid UA spend.",
        learnings: "Short form content with gameplay hooks (first 3 seconds showing a dramatic play) consistently outperformed talking-head style reviews by 3x in watch time and 2x in click-through.",
      },
    },
    {
      num: "02",
      brand: "INFINIX GT30 PRO",
      category: "Consumer Electronics · Product Launch",
      color: "#00C853",
      accentLight: "#4ade80",
      objective: "Create strong buzz for the launch of the Infinix GT30 Pro Gaming Edition smartphone.",
      strategy: "Partnered with high engagement gaming creators to drive credibility and showcase real in game performance benchmarks.",
      execution: [
        "Product focused short videos featuring real gameplay on the device",
        "Authentic creator opinions and honest benchmark comparisons",
        "Barter collaboration model to maximize ROI without paid fees",
      ],
      stats: [
        { value: "3.6M+", label: "Views", icon: "Eye" },
        { value: "200K+", label: "Likes", icon: "ThumbsUp" },
        { value: "4", label: "Influencers", icon: "Star" },
      ],
      fullDetail: {
        background: "Infinix GT30 Pro needed a gaming  focused launch strategy to reach India's growing PC to mobile gaming converter audience. Traditional tech review channels weren't cutting through the brand needed creators who actually game.",
        approach: "We curated 4 macro gaming creators with combined reach of 8M+, structured a barter deal (device gifting and usage rights), and co-developed content briefs that felt native to each creator's style not scripted tech ads.",
        results: "3.6M views across 4 creators in 2 weeks. The cost efficiency was remarkable: all delivered through barter, making the effective CPV near zero. The 200K likes signal strong purchase intent among the gaming demographic.",
        learnings: "Barter deals work best when creators are genuinely enthusiastic about the product. We pre-screened all 4 creators to ensure they were already gaming phone users authenticity drove the engagement numbers.",
      },
    },
    {
      num: "03",
      brand: "METASPACE",
      category: "Web3 · Podcast · Esports",
      color: "#06B6D4",
      accentLight: "#22d3ee",
      objective: "Shift MetaSpace's perception from just another gaming platform to a Web3 esports authority, and boost visibility for their new podcast.",
      strategy: "Used gaming creators to push Shorts, Reels, Stories, and community posts positioning the podcast as a must watch for gaming enthusiasts transitioning to Web3.",
      execution: [
        "Community-driven engagement through creator Discord and Telegram shoutouts",
        "Positioned podcast as inside knowledge for Web3 gaming early adopters",
        "Cross-platform amplification: YouTube Shorts and Instagram Reels and Twitter threads",
      ],
      stats: [
        { value: "1M+", label: "Total Views", icon: "Eye" },
        { value: "100K+", label: "Podcast Views", icon: "Mic2" },
      ],
      fullDetail: {
        background: "MetaSpace sat at the intersection of gaming and Web3 — an exciting but niche space. Their podcast had strong content but lacked distribution. The challenge was converting gaming audiences (skeptical of crypto) into Web3-curious listeners.",
        approach: "We reframed the messaging away from Web3 (which triggers skepticism) toward the future of esports earnings — a message that resonated immediately with gaming creators and their audiences. Creator selection focused on channels where the audience was already discussing pro gaming careers.",
        results: "1M total views across platforms with 100K dedicated podcast views — a 10% conversion rate from content views to long-form podcast consumption, far above the industry average of 1–2%.",
        learnings: "Framing matters more than reach. A perfectly framed message through a mid-tier creator consistently outperforms a generic message through a mega creator. This campaign was proof.",
      },
    },
  ],

  team: [
    {
      name: "Rohit Chattopadhyay",
      role: "Co-Founder & CEO",
      icon: "Rocket",
      color: "#ffffff",
      linkedin: "https://www.linkedin.com/in/rohit-chattopadhyay/",
      description: "Leading the vision and strategy at Brand Brokers. Focused on building a performance-driven ecosystem for creators and brands. Rohit ensures that every campaign aligns with our core values of transparency and excellence.",
    },
    {
      name: "Arkajyoti Majumdar",
      role: "Co-Founder & CMO",
      icon: "BarChart",
      color: "#e5e7eb",
      linkedin: "https://www.linkedin.com/in/arkajyoti-majumdar/",
      description: "The mastermind behind our growth marketing strategies. specialized in data-driven performance marketing and creator-led brand building for Gen-Z audiences. Arka turns insights into results.",
    },
    {
      name: "Sayak Daw",
      role: "Co-Founder & Head of Partnerships",
      icon: "Handshake",
      color: "#d1d5db",
      linkedin: "https://www.linkedin.com/in/sayak-daw/",
      description: "Bridging the gap between global brands and top-tier creators. Sayak focuses on building long-term, sustainable partnerships that deliver value to all stakeholders in the creator economy.",
    },
  ],

  clients: [
    { kind: "client", row: 1, name: "Samsung", logo: "/clients/samsung.png" },
    { kind: "client", row: 1, name: "Rooter", logo: "/clients/rooter.svg" },
    { kind: "client", row: 1, name: "Infinix", logo: "/clients/infinix.svg" },
    { kind: "client", row: 1, name: "Mobile Legends", logo: "/clients/mobilelegends.svg" },
    { kind: "client", row: 1, name: "Meta", logo: "/clients/meta.png" },
    { kind: "client", row: 1, name: "Gamerji", logo: "/clients/gamerji.svg" },
    { kind: "client", row: 1, name: "IQ Option", logo: "/clients/iqoption.svg" },
    { kind: "client", row: 1, name: "Apple", logo: "/clients/apple.png" },
    { kind: "client", row: 1, name: "STAN", logo: "/clients/stan.png" },
    { kind: "client", row: 2, name: "Indus Battle Royale", logo: "/clients/indus.svg" },
    { kind: "client", row: 2, name: "BigCash", logo: "/clients/bigcash.svg" },
    { kind: "client", row: 2, name: "WePlay", logo: "/clients/weplay.svg" },
    { kind: "client", row: 2, name: "Krafton", logo: "/clients/krafton.svg" },
    { kind: "client", row: 2, name: "MetaSpace", logo: "/clients/metaspace.svg" },
    { kind: "client", row: 2, name: "MS5", logo: "/clients/ms5.svg" },
    { kind: "client", row: 2, name: "Nodwin Gaming", logo: "/clients/nodwin.svg" },
    { kind: "client", row: 2, name: "Jackaroo King", logo: "/clients/jackaroo.svg" },
    { kind: "client", row: 2, name: "MPL", logo: "/clients/mpl.svg" },
    { kind: "stat", num: "1500+", label: "Creators" },
    { kind: "stat", num: "50+", label: "Brand Campaigns" },
    { kind: "stat", num: "3.6M+", label: "Views Generated" },
    { kind: "stat", num: "100%", label: "Transparent Reporting" },
  ],

  roster: [
    {
      handle: "@techwithalex",
      niche: "Tech & Gadgets",
      followers: "2.4M",
      icon: "Monitor",
      description: "Alex is a leading tech reviewer specializing in cutting-edge consumer electronics and smart home ecosystems. Known for detailed deep-dives and honest performance benchmarks.",
      socials: {
        instagram: "https://instagram.com",
        youtube: "https://youtube.com",
        facebook: "https://facebook.com",
        snapchat: "https://snapchat.com",
      },
    },
    {
      handle: "@lifewithsara",
      niche: "Lifestyle & Beauty",
      followers: "1.8M",
      icon: "Sparkles",
      description: "Sara bridges the gap between high-end luxury and everyday accessibility. Her content focuses on mindful living, sustainable beauty, and aesthetic home organization.",
      socials: {
        instagram: "https://instagram.com",
        youtube: "https://youtube.com",
        snapchat: "https://snapchat.com",
      },
    },
    {
      handle: "@gamingwithkai",
      niche: "Gaming & Esports",
      followers: "3.1M",
      icon: "Gamepad2",
      description: "Kai is a top-tier esports commentator and variety streamer. He commands a highly engaged community focused on competitive FPS titles and indie game discoveries.",
      socials: {
        instagram: "https://instagram.com",
        youtube: "https://youtube.com",
        facebook: "https://facebook.com",
      },
    },
    {
      handle: "@fitnessbyjordan",
      niche: "Health & Fitness",
      followers: "980K",
      icon: "Dumbbell",
      description: "Jordan specializes in functional strength training and nutritional science. He provides science-backed workout programs and realistic lifestyle transformations.",
      socials: {
        instagram: "https://instagram.com",
        youtube: "https://youtube.com",
        snapchat: "https://snapchat.com",
      },
    },
    {
      handle: "@foodiemaya",
      niche: "Food & Travel",
      followers: "1.2M",
      icon: "Utensils",
      description: "Maya explores global cultures through their culinary heritage. From street food gems to Michelin-starred kitchens, she tells stories through every bite.",
      socials: {
        instagram: "https://instagram.com",
        youtube: "https://youtube.com",
        facebook: "https://facebook.com",
      },
    },
    {
      handle: "@musicbyryan",
      niche: "Music & Entertainment",
      followers: "2.7M",
      icon: "Music",
      description: "Ryan is a multi-instrumentalist and producer sharing the secrets of music creation. He blends technical tutorials with viral entertainment and performance art.",
      socials: {
        instagram: "https://instagram.com",
        youtube: "https://youtube.com",
        snapchat: "https://snapchat.com",
      },
    },
  ],
};
